version: '3'
services:
  db:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    environment:
      - DEPLOY_SSH_KEYS="~/.ssh/id_rsa.YOUR-DEPLOY-KEY"
      - AWS_ACCESS_KEY_ID="YOUR-ACCESS-KEY-ID"
      - AWS_SECRET_ACCESS_KEY="YOUR-SECRET-ACCESS-KEY"
    command: bundle exec foreman start
    volumes:
      - .:/rails_app
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
      - redis
volumes:
  db_data:
